import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/ModeToggle";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system" // System preference will be the default
          enableSystem
          disableTransitionOnChange
        >
          {/* <div className="min-h-screen bg-gray-100 dark:bg-gray-900 text-gray-800 dark:text-gray-100"> */}
          {/* Global container ensures dark mode for all children */}
          {/* <header className="p-4 shadow-md bg-white-200 dark:bg-gray-800">
              <div className="container mx-auto flex justify-between items-center">
                <h1 className="text-xl font-bold">BuyBuddy</h1>
                <ModeToggle />
              </div>
            </header> */}
          <main>{children}</main>
          {/* <Navbar /> */}
          {/* <Footer /> */}

          {/* </div> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
